name: chat_app
description: A simple console-based chat application.
version: 1.0.0
# repository: https://github.com/miracleRichard5124/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
   path: ^1.8.0
   http: ^0.13.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
